### PR TITLE
New design

### PR DESCRIPTION
**Pull request by bulletfactory**
Basic styles and site structure in place. Still some work to do on navigation, getting the logos you'd like as svg files (if possible), and some alignment - but this is functional and will give you a sense of how the site has progressed.

### CODE REVIEW

**Comment by bulletfactory** [comment]
Tablet and Mobile Nav still to be added.
Gradients instead of flat, dark colored sections


Desktop
graphite_desktop

Tablet
graphite_tablet

Mobile
graphite_mobile

**Comment by JeanFred** [comment]
Do you want this to be merged @bulletfactory ? It all looks very good to me, but I can’t tell if you would prefer to do more work on it first :)

**Comment by obfuscurity** [comment]
Hands off for now, I'm trying to find time to continue working on the branch.

Thanks,
Jason

**Comment by obfuscurity** [comment]
Merging this in so I can rebase and continue on top of @bulletfactory's fine work.

**Pull request merged**
